from tkinter import *
from tkinter import Tk
class payrollsystem:
    def __init__(self, root, ):
        self.root = root
        self.root.title("Payroll Managenment System")
        self.root.geometry("1350x700")
        self.root.config(bg="black")
        title=Label(self.root,text="payroll managenment system",font=("time new roman",30,"bold"),bg="black",fg="white",anchor="w",padx=10).place(x=0,y=0,relwidth=1)
        Frame1=Frame(self.root,bd=5,relief=RIDGE,bg="black")
        title2 = Label(Frame1,text="Empyloee Details", font=("time new roman", 15), bg="blue",fg="white", anchor="w", padx=10).place(x=0, y=0, relwidth=1)
        Frame1.place(x=10,y=70,width=1250,height=620)
        lb1_ID = Label(Frame1, text="Employee ID", font=("time new roman", 15), bg="blue", fg="white").place(x=10, y=50)
        text_ID = Entry(Frame1,font=("time new roman", 15), bg="light yellow", fg="black").place(x=170,y=50)
        lb1_department = Label(Frame1, text="Department", font=("time new roman", 15), bg="blue", fg="white").place(x=800, y=50)
        text_department = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=960, y=50)
        lb1_designation = Label(Frame1, text="designation", font=("time new roman", 15), bg="blue", fg="white").place(x=10, y=120)
        text_designtion = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=170, y=120)
        lb1_dob = Label(Frame1, text="D.O.B", font=("time new roman", 15), bg="blue", fg="white").place(x=800, y=120)
        text_dob = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=960, y=120)
        lb1_Email = Label(Frame1, text="email", font=("time new roman", 15), bg="blue", fg="white", ).place(x=10, y=180)
        text_Email = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=170, y=180)
        lb1_doj = Label(Frame1, text="D.O.J", font=("time new roman", 15), bg="blue", fg="white", ).place(x=800, y=180)
        text_doj = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=960, y=180)
        lb1_Name = Label(Frame1, text="Name", font=("time new roman", 15), bg="blue",fg="white" ).place(x=10, y=240)
        text_Name = Entry(Frame1,font=("time new roman",15),bg="light yellow",fg="black").place(x=170,y=240)
        lb1_contectno = Label(Frame1, text="contect no", font=("time new roman", 15), bg="blue", fg="white").place(x=800, y=240)
        text_contectno = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=960, y=240)
        lb1_age = Label(Frame1, text="age", font=("time new roman", 15), bg="blue", fg="white" ).place(x=10, y=300)
        text_age = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=170, y=300)
        lb1_salary = Label(Frame1, text="salary", font=("time new roman", 15), bg="blue", fg="white").place(x=800, y=300)
        text_salary = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=960, y=300)
        lb1_gender = Label(Frame1, text="gender", font=("time new roman", 15), bg="blue", fg="white" ).place(x=10, y=360)
        text_gender = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=170, y=360)
        lb1_Address = Label(Frame1, text="Address", font=("time new roman", 15), bg="blue", fg="white").place(x=800, y=360)
        text_Address = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=960, y=360)
        lb1_searchemp = Label(Frame1, text="Search emp:", font=("time new roman", 15), bg="blue", fg="white").place(x=400,y=440)
        text_searchemp = Entry(Frame1, font=("time new roman", 15), bg="light yellow", fg="black").place(x=560, y=440)
        btn_search = Button(Frame1,text="Search",font=( "time new roman", 13,"bold"), bg="light yellow", fg="black").place(x=560, y=500)
        btn_addrecord = Button(Frame1, text="Add Record", font=("time new roman", 13, "bold"), bg="light yellow", fg="black").place(x=560, y=900)
        btn_update = Button(Frame1, text="Update", font=("time new roman", 13, "bold"), bg="light yellow",fg="black").place(x=960, y=550)
        btn_delete = Button(Frame1, text="Delete", font=("time new roman", 13, "bold"), bg="light yellow",fg="black").place(x=860, y=550)
        btn_clear = Button(Frame1, text="Clear", font=("time new roman", 13, "bold"), bg="light yellow",fg="black").place(x=760, y=550)

root = Tk()
obj = payrollsystem(root)
root.mainloop()
